# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(username: "guest", password: "password")
User.create(username: "tyler", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478046196/Fields2_xkwxzq.jpg")
User.create(username: "rhonda", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_500/v1478795201/12088435_10208158842873435_5225147686812853100_n_aozrwq.jpg")
User.create(username: "tom", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478795476/jlz7sshnrcramoh8wuaq.jpg")
User.create(username: "austin", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478795611/vmhwwvgwfblxopgfy6zg.jpg")
User.create(username: "levi", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478795709/juym51yy6sp4v4gb2yfn.jpg")
User.create(username: "caleb", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478795947/rbjy4uwzwafteg3yrtzq.jpg")
User.create(username: "ashley", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478796020/xbwfh0kxdql7cbhh07g3.jpg")
User.create(username: "shirley", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478796119/kzyn6qbnkrpy2vkt0rsn.jpg")
User.create(username: "dan", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478796284/smauownmkhbfxrsvxo8n.jpg")
User.create(username: "kris", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478796386/udyb9bwj1l0u6znw5rrh.jpg")
User.create(username: "ryan", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478797316/vjizg9zuwzhpazxzvgbc.jpg")
User.create(username: "seth", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478797396/b5sgek7jd8qaxnoaescb.jpg")
User.create(username: "justin", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478797461/imp8dlxir846hbyc1vo8.jpg")
User.create(username: "eli", password: "password", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478797671/re8rfkn3fngbjdizb2aq.jpg")

Roaster.create(name: "None Given")
Roaster.create(name: "Safe Camp Coffee", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478278838/1qfPJuBe_iye7wm.jpg")
Roaster.create(name: "James Coffee Co.", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478282408/5061261_300x300_szcbi4.jpg")
Roaster.create(name: "Starbucks", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478284914/starbuckslogo_gmrnyn.png")
Roaster.create(name: "Philz Coffee", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478285393/P13O4djR_iv9yat.png")
Roaster.create(name: "Sightglass Coffee", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478285880/Sightglass-logo_qdds8y.jpg")
Roaster.create(name: "Ritual Coffee Roasters", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478797875/ruoik2l8cewrick0hfgb.jpg")
Roaster.create(name: "Bee Coffee Roasters", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478798036/gdlvjmncvshujymxmvyi.jpg")
Roaster.create(name: "Tinker Coffee Co.", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478798207/cnplirppcxojtke1qlwe.png")
Roaster.create(name: "Dunkin' Donuts", picture_url: "http://res.cloudinary.com/dfmvfna21/image/upload/v1478798603/z13e26adq7oca1xoiuwc.jpg")

Drink.create(name: 'Banner Dark', roaster_id: 6, roast_type: "Dark", description: "Notes of dark chocolate and brown sugar meet rich undertones of vanilla and maple.")
Drink.create(name: 'Caffè Verona', roaster_id: 4, roast_type: "Dark", description: "Well-balanced and rich with a dark cocoa texture. Pair with dark chocolate to bring out even more sweetness.")
Drink.create(name: 'Canopy of Heaven', roaster_id: 5, roast_type: "Light", description: "Featuring a classic lighter roast profile, this blend really shakes things up with its unique flavor profile. The Canopy of Heaven bursts with lively and complex flavors that will get your attention.")
Drink.create(name: 'Columbia El Meridiano, Tolima', roaster_id: 6, roast_type: "Medium", description: "Round and approachable, flavors of red grape and orange zest, soft spiced cider aromas, and a toffee like sweetness.")
Drink.create(name: 'Ethiopia "AYEHU" RFA', roaster_id: 3, roast_type: "Medium", description: "Wild Ethiopian varieties. Natural processing, Sweet red berry, caramel, clean, juicy, and dark chocolate tasting notes. From the Awi Zone, Amhara Region. Grown at an altitude of 1600-1700m. Roasted in San Diego, CA.")
Drink.create(name: 'Ethiopian Harar', roaster_id: 2, roast_type: "Medium", description: "Heavy-bodied, spicy and fragrant, Ethiopian Harrar coffee is a wild and exotic dry processed (natural) Arabica coffee that is grown on small farms in the Oromia region (formerly Harrar) in southern Ethiopia at elevations between 4,500 and 6,300 feet. The province of Harrar, is east of Addis Ababa, the country's capitol.")
Drink.create(name: 'Guatemala "TG-LAB FÁTIMA"', roaster_id: 3, roast_type: "Medium", description: "Juicy, blood orange, macadamia nut, and creamy full body tasting notes. From the Alta Varapaz region. Grown at an altitude of 1200-1450m. Roasted in San Diego, CA.")
Drink.create(name: 'Honduras Santa Rosa De Copan', roaster_id: 2, roast_type: "Dark", description: "Lote Mendez has a burned sugar sweetness, with high % dark chocolate bar, roasted cacao nibs, sweet pipe tobacco, and honey wheat. A BIG bodied cup.")
Drink.create(name: 'Juturna Blend', roaster_id: 3, roast_type: "Medium-Light", description: "Roasted for Circa Survive Juturna 10 Year Anniversary tour. Limited to 200 bags. Roasted in San Diego, CA.")
Drink.create(name: 'Kenya Kangunu AA', roaster_id: 6, roast_type: "Light", description: "This coffee boasts complexity and clarity. Lush and syrupy with hints of tart mandarin, blackberry, and brown sugar.")
Drink.create(name: 'Night Owl', roaster_id: 3, roast_type: "Dark", description: "Organic blend of rich heavy bodied coffee with dark notes of hazelnut and maple syrup. Roasted in San Diego, CA.")
Drink.create(name: 'Philtered Soul', roaster_id: 5, roast_type: "Medium", description: "Philtered Soul has distinctively nutty flavors with a satisfying aftertaste that’s sure to please your soul. It’s become the blend of choice for many who frequent our cafes.")
Drink.create(name: 'Pike Place', roaster_id: 4, roast_type: "Medium", description: "A smooth, well-rounded blend of Latin American coffees with subtly rich flavors of cocoa and toasted nuts, it’s perfect for every day.")
Drink.create(name: 'SFMOMA', roaster_id: 6, roast_type: "Light", description: "Vivid flavors of citrus fruit give way to sweet, deep caramel and milk chocolate undertones.")
Drink.create(name: 'Tantalizing Turkish', roaster_id: 5, roast_type: "Medium", description: "Tantalizing Turkish is exceptionally flavorful and unique due to its intensely rich and familiar characteristics of traditional Turkish coffee.")
Drink.create(name: 'Veranda Blend', roaster_id: 4, roast_type: "Light", description: "A shorter roast time, lighter body and mellow flavors. Subtle with delicate nuances of soft cocoa and lightly toasted nuts.")
Drink.create(name: 'White Owl', roaster_id: 3, roast_type: "Light", description: "An organic blend with radiant sweet bright red berry, creamy vanilla and a light coca finish. Roasted in San Diego, CA.")
Drink.create(name: 'Willow Blend', roaster_id: 4, roast_type: "Light", description: "The lighter roast reveals the juicy lemony notes we love to discover in African coffee, followed by a crisp finish courtesy of the Latin American beans. Graceful with a deep, enveloping flavor, it's everything you'd want from a light roast—and much more than you'd expect.")

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 1, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 5, description: nil, user_id: 1, drink_id: 1)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 1)
Rating.create(checkin_rating: 3, description: nil, user_id: 3, drink_id: 1)
Rating.create(checkin_rating: nil, description: nil, user_id: 4, drink_id: 1)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 1)
Rating.create(checkin_rating: nil, description: nil, user_id: 5, drink_id: 1)
Rating.create(checkin_rating: 5, description: nil, user_id: 6, drink_id: 1)
Rating.create(checkin_rating: nil, description: nil, user_id: 9, drink_id: 1)
Rating.create(checkin_rating: 5, description: nil, user_id: 10, drink_id: 1)
Rating.create(checkin_rating: nil, description: nil, user_id: 11, drink_id: 1)
Rating.create(checkin_rating: 2, description: nil, user_id: 12, drink_id: 1)
Rating.create(checkin_rating: 4, description: nil, user_id: 14, drink_id: 1)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 1)
Rating.create(checkin_rating: nil, description: nil, user_id: 15, drink_id: 1)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 2, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 2)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 2)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 2)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 2)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 2)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 2)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 2)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 2)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 2)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 2)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 2)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 2)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 2)
Rating.create(checkin_rating: nil, description: nil, user_id: 4, drink_id: 2)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 3, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 3)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 3)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 3)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 3)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 3)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 3)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 3)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 3)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 3)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 3)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 3)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 3)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 3)
Rating.create(checkin_rating: nil, description: nil, user_id: 4, drink_id: 3)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 4, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 4)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 4)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 4)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 4)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 4)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 4)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 4)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 4)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 4)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 4)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 4)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 4)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 4)
Rating.create(checkin_rating: nil, description: nil, user_id: 4, drink_id: 4)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 5, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 5)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 5)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 5)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 5)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 5)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 5)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 5)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 5)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 5)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 5)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 5)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 5)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 5)
Rating.create(checkin_rating: nil, description: nil, user_id: 4, drink_id: 5)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 6, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 6)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 6)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 6)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 6)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 6)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 6)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 6)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 6)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 6)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 6)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 6)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 6)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 6)
Rating.create(checkin_rating: nil, description: nil, user_id: 4, drink_id: 6)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 7, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 7)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 7)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 7)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 7)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 7)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 7)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 7)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 7)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 7)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 7)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 7)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 7)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 7)
Rating.create(checkin_rating: 2, description: "Ok", user_id: 2, drink_id: 7)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 8, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 8)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 8)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 8)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 8)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 8)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 8)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 8)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 8)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 8)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 8)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 8)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 8)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 8)
Rating.create(checkin_rating: 2, description: "Ok", user_id: 2, drink_id: 8)

Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 9)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 9)
Rating.create(checkin_rating: 5, description: "Amazing!", user_id: 1, drink_id: 9)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 9)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 9)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 9)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 9)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 9)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 9)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 9)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 9)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 9)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 9)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 9)
Rating.create(checkin_rating: 2, description: "Ok", user_id: 2, drink_id: 9)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 10, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 10)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 10)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 10)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 10)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 10)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 10)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 10)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 10)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 10)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 10)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 10)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 10)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 10)
Rating.create(checkin_rating: 2, description: "Ok", user_id: 2, drink_id: 10)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 11, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 11)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 11)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 11)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 11)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 11)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 11)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 11)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 11)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 11)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 11)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 11)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 11)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 11)
Rating.create(checkin_rating: 2, description: "Ok", user_id: 2, drink_id: 11)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 12, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 12)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 12)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 12)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 12)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 12)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 12)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 12)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 12)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 12)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 12)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 12)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 12)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 12)
Rating.create(checkin_rating: 2, description: "Ok", user_id: 2, drink_id: 12)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 13, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 13)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 13)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 13)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 13)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 13)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 13)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 13)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 13)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 13)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 13)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 13)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 13)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 13)
Rating.create(checkin_rating: 2, description: "Ok", user_id: 2, drink_id: 13)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 14, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 14)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 14)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 14)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 14)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 14)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 14)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 14)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 14)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 14)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 14)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 14)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 14)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 14)
Rating.create(checkin_rating: 2, description: "Ok", user_id: 2, drink_id: 14)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 15, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 15)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 15)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 15)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 15)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 15)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 15)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 15)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 15)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 15)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 15)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 15)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 15)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 15)
Rating.create(checkin_rating: 2, description: "Ok", user_id: 2, drink_id: 15)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 16, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 16)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 16)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 16)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 16)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 16)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 16)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 16)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 16)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 16)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 16)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 16)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 16)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 16)
Rating.create(checkin_rating: 2, description: "Ok", user_id: 2, drink_id: 16)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 17, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 17)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 17)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 17)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 17)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 17)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 17)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 17)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 17)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 17)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 17)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 17)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 17)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 17)
Rating.create(checkin_rating: 2, description: "Ok", user_id: 2, drink_id: 17)

Rating.create(checkin_rating: nil, description: nil, user_id: 1, drink_id: 18, picture_url:"http://res.cloudinary.com/dfmvfna21/image/upload/c_scale,h_199/v1478563599/coffee-cup-outline_318-39738_sl1xhs.jpg")
Rating.create(checkin_rating: 4, description: "Really Good", user_id: 2, drink_id: 18)
Rating.create(checkin_rating: nil, description: nil, user_id: 8, drink_id: 18)
Rating.create(checkin_rating: 4, description: nil, user_id: 8, drink_id: 18)
Rating.create(checkin_rating: 5, description: nil, user_id: 3, drink_id: 18)
Rating.create(checkin_rating: nil, description: nil, user_id: 2, drink_id: 18)
Rating.create(checkin_rating: 4, description: nil, user_id: 9, drink_id: 18)
Rating.create(checkin_rating: 5, description: nil, user_id: 14, drink_id: 18)
Rating.create(checkin_rating: nil, description: nil, user_id: 7, drink_id: 18)
Rating.create(checkin_rating: 2, description: nil, user_id: 15, drink_id: 18)
Rating.create(checkin_rating: 4, description: nil, user_id: 12, drink_id: 18)
Rating.create(checkin_rating: nil, description: nil, user_id: 14, drink_id: 18)
Rating.create(checkin_rating: 4, description: nil, user_id: 5, drink_id: 18)
Rating.create(checkin_rating: 5, description: nil, user_id: 8, drink_id: 18)
Rating.create(checkin_rating: 2, description: "Ok", user_id: 2, drink_id: 18)
